### ISSUE TITLE
PHP Warning – Use of undefined constant global_convert_from

### ISSUE THREAD

**Issue by dartiss** [dartiss/open-currency-converter#29]
component: “Plugin: artiss-currency-converter”
file: “wp-content/plugins/artiss-currency-converter/includes/convert-currency.php”
line: 93
message: “Use of undefined constant global_convert_from – assumed ‘global_convert_from’ (this will throw an Error in a future version of PHP)”

https://wordpress.org/support/topic/php-warning-use-of-undefined-constant-global_convert_from/

**Comment by saravana87** [comment]
It can be fixed by adding double quotes
define ("global_convert_from")

Thanks

**Comment by Matej4545** [comment]
Hi,
could you please push a fix for this bug in the near future? As @saravana87 said, it can be simply fixed (ln 93 and 100 in convert-currency.php). It has been there since PHP 7.2 and I discovered that when combined with Elementor, it outputs the console message directly to the web, which is annoying at least. I quick-fixed it in source code, but I guess this could be an issue for the majority of the users.

**Comment by dartiss** [comment]
Hi @Matej4545 - I'll try and get this pushed out over the next week or two.

**Comment by dartiss** [comment]
@Matej4545 Released!
